#ifndef SMART_POWER_CASE_V2_HW_CONFIG_H
#define SMART_POWER_CASE_V2_HW_CONFIG_H

#define WKUP_PIN GPIO_PIN_0
#define WKUP_GPIO_PORT GPIOA
#define WKUP_EXTI_IRQn EXTI0_IRQn
#define BUTTON_5_PIN GPIO_PIN_2
#define BUTTON_5_GPIO_PORT GPIOA
#define SPI1_CS_PIN GPIO_PIN_4
#define SPI1_CS_GPIO_PORT GPIOA
#define BUTTON_4_PIN GPIO_PIN_6
#define BUTTON_4_GPIO_PORT GPIOA
#define BUTTON_4_EXTI_IRQn EXTI9_5_IRQn
#define SPI_DC_PIN GPIO_PIN_0
#define SPI_DC_GPIO_PORT GPIOB
#define SPI_RST_PIN GPIO_PIN_1
#define SPI_RST_GPIO_PORT GPIOB
#define LCD_EN_PIN GPIO_PIN_2
#define LCD_EN_GPIO_PORT GPIOB
#define LCD_BLK_PIN GPIO_PIN_10
#define LCD_BLK_GPIO_PORT GPIOB
#define EN_12V_PIN GPIO_PIN_12
#define EN_12V_GPIO_PORT GPIOB
#define BUTTON_2_PIN GPIO_PIN_13
#define BUTTON_2_GPIO_PORT GPIOB
#define BUTTON_2_EXTI_IRQn EXTI15_10_IRQn
#define BUTTON_1_PIN GPIO_PIN_14
#define BUTTON_1_GPIO_PORT GPIOB
#define BUTTON_1_EXTI_IRQn EXTI15_10_IRQn
#define BUTTON_3_PIN GPIO_PIN_15
#define BUTTON_3_GPIO_PORT GPIOB
#define BUTTON_3_EXTI_IRQn EXTI15_10_IRQn
#define PWM_BUZZ_PIN GPIO_PIN_8
#define PWM_BUZZ_GPIO_PORT GPIOA
#define USB_RESET_PIN GPIO_PIN_10
#define USB_RESET_GPIO_PORT GPIOA
#define INT2_ACC_PIN GPIO_PIN_4
#define INT2_ACC_GPIO_PORT GPIOB
#define INT2_ACC_EXTI_IRQn EXTI4_IRQn
#define INT1_ACC_PIN GPIO_PIN_5
#define INT1_ACC_GPIO_PORT GPIOB
#define INT1_ACC_EXTI_IRQn EXTI9_5_IRQn

#define MAGIC_DFU_VALUE (0x1AAA)
#define TAPER_CURRENT              150      // Current cut-off charging for BQ25895 and BQ27441
#define MAX_VOLTAGE_LIION          4200     // Max charge voltage for battery

#endif //SMART_POWER_CASE_V2_HW_CONFIG_H
