name: build

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build: # make sure build/ci work properly
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v2

      - name: Install git
        run: npm install git

      - name: Download arm-none-eabi-gcc
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '7-2018-q2'

      - name: Create Build folder
        run: cmake -E make_directory ${{runner.workspace}}/smart-power-case-v2/build

      - name: Configure CMake project
        working-directory: ${{runner.workspace}}/smart-power-case-v2/build
        shell: bash
        run: cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -D_WHERE_BUILD=Cloud ..

      - name: Build project
        working-directory: ${{runner.workspace}}/smart-power-case-v2/build
        shell: bash
        run: make -j11


      - name: Upload Artifacts HEX
        uses: actions/upload-artifact@v2
        with:
          name: "Download artifacts - HEX"
          path: ${{runner.workspace}}/smart-power-case-v2/build/*.hex

      - name: Upload Artifacts BIN
        uses: actions/upload-artifact@v2
        with:
          name: "Download artifacts - BIN"
          path: ${{runner.workspace}}/smart-power-case-v2/build/*.bin